// frontend-svelte-backup/src/pages/agents/HTTPAgentEditor.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import { 
    CreateHTTPAgentFull, 
    GetHTTPAgentFull, 
    UpdateHTTPAgentFull, 
    DeleteHTTPAgentFull,
    CreateHTTPEndpoint,
    UpdateHTTPEndpoint,
    DeleteHTTPEndpoint,
    TestHTTPEndpoint
  } from '../../../wailsjs/go/main/App.js';
  import EndpointEditor from './EndpointEditor.svelte';
  import { Modal } from '../../components/modal';
  
  export let agentConfigId = null;  // Se fornecido, carrega agent existente
  export let onClose = null;
  
  const dispatch = createEventDispatcher();
  
  // Estado do agent
  let loading = true;
  let saving = false;
  let error = '';
  let httpAgentId = null;
  
  // Campos do AgentConfig
  let name = '';
  let displayName = '';
  let description = '';
  let model = 'gpt-4o-mini';
  let systemPrompt = '';
  let enabled = true;
  
  // Campos específicos do HTTPAgent
  let baseURL = '';
  let authType = 'none';
  let authConfig = {};
  let defaultHeaders = [];
  let timeoutSeconds = 30;
  let retryCount = 3;
  let endpoints = [];
  
  // Estado de edição
  let editingEndpoint = null;
  let showEndpointEditor = false;
  let showTestModal = false;
  let testEndpoint = null;
  let testParams = '';
  let testResult = '';
  let testError = '';
  let testing = false;
  
  // Tipos de autenticação
  const authTypes = [
    { value: 'none', label: 'Sem autenticação' },
    { value: 'api_key', label: 'API Key' },
    { value: 'bearer', label: 'Bearer Token' },
    { value: 'basic', label: 'HTTP Basic' },
    { value: 'oauth2', label: 'OAuth 2.0' },
  ];
  
  // Tipos de grant OAuth2
  const oauth2GrantTypes = [
    { value: 'client_credentials', label: 'Client Credentials' },
    { value: 'authorization_code', label: 'Authorization Code (requer interação)' },
  ];
  
  // Modelos disponíveis
  const availableModels = [
    'gpt-4o-mini',
    'gpt-4o',
    'gpt-4-turbo',
    'gpt-3.5-turbo',
  ];
  
  onMount(async () => {
    if (agentConfigId) {
      await loadAgent();
    } else {
      loading = false;
    }
  });
  
  async function loadAgent() {
    loading = true;
    error = '';
    
    try {
      const agent = await GetHTTPAgentFull(agentConfigId);
      
      name = agent.name;
      displayName = agent.display_name;
      description = agent.description;
      model = agent.model || 'gpt-4o-mini';
      systemPrompt = agent.system_prompt || '';
      enabled = agent.enabled;
      
      httpAgentId = agent.http_agent_id;
      baseURL = agent.base_url;
      authType = agent.auth_type || 'none';
      timeoutSeconds = agent.timeout_seconds || 30;
      retryCount = agent.retry_count || 3;
      
      try {
        authConfig = agent.auth_config ? JSON.parse(agent.auth_config) : {};
      } catch (e) {
        authConfig = {};
      }
      
      try {
        const headers = agent.default_headers ? JSON.parse(agent.default_headers) : {};
        defaultHeaders = Object.entries(headers).map(([key, value]) => ({ key, value }));
      } catch (e) {
        defaultHeaders = [];
      }
      
      endpoints = agent.endpoints || [];
    } catch (err) {
      error = 'Erro ao carregar agente: ' + (err.message || err);
    } finally {
      loading = false;
    }
  }
  
  async function handleSave() {
    if (!name.trim()) {
      error = 'Nome é obrigatório';
      return;
    }
    if (!displayName.trim()) {
      error = 'Nome de exibição é obrigatório';
      return;
    }
    if (!baseURL.trim()) {
      error = 'URL base é obrigatória';
      return;
    }
    
    saving = true;
    error = '';
    
    try {
      // Converte headers para JSON
      const headersObj = {};
      for (const h of defaultHeaders) {
        if (h.key.trim()) {
          headersObj[h.key.trim()] = h.value;
        }
      }
      const headersJSON = JSON.stringify(headersObj);
      const authConfigJSON = JSON.stringify(authConfig);
      
      if (agentConfigId) {
        // Atualiza existente
        await UpdateHTTPAgentFull(
          agentConfigId,
          displayName,
          description,
          model,
          systemPrompt,
          enabled,
          baseURL,
          authType,
          authConfigJSON,
          headersJSON,
          timeoutSeconds,
          retryCount
        );
      } else {
        // Cria novo
        const result = await CreateHTTPAgentFull(
          name,
          displayName,
          description,
          model,
          systemPrompt,
          enabled,
          baseURL,
          authType,
          authConfigJSON,
          headersJSON,
          timeoutSeconds,
          retryCount
        );
        agentConfigId = result.id;
        httpAgentId = result.http_agent_id;
      }
      
      dispatch('saved');
      
      if (onClose) {
        onClose();
      }
    } catch (err) {
      error = 'Erro ao salvar: ' + (err.message || err);
    } finally {
      saving = false;
    }
  }
  
  async function handleDelete() {
    if (!confirm('Tem certeza que deseja excluir este agente HTTP e todos os seus endpoints?')) {
      return;
    }
    
    try {
      await DeleteHTTPAgentFull(agentConfigId);
      dispatch('deleted');
      if (onClose) {
        onClose();
      }
    } catch (err) {
      error = 'Erro ao excluir: ' + (err.message || err);
    }
  }
  
  function addHeader() {
    defaultHeaders = [...defaultHeaders, { key: '', value: '' }];
  }
  
  function removeHeader(index) {
    defaultHeaders = defaultHeaders.filter((_, i) => i !== index);
  }
  
  function openEndpointEditor(endpoint = null) {
    editingEndpoint = endpoint;
    showEndpointEditor = true;
  }
  
  async function handleEndpointSave(endpointData) {
    try {
      if (endpointData.id) {
        // Atualiza existente
        await UpdateHTTPEndpoint(
          endpointData.id,
          endpointData.name,
          endpointData.description,
          endpointData.method,
          endpointData.path_template,
          endpointData.query_template,
          endpointData.headers_json,
          endpointData.body_template,
          endpointData.parameters,
          endpointData.response_template
        );
      } else {
        // Cria novo
        await CreateHTTPEndpoint(
          httpAgentId,
          endpointData.name,
          endpointData.description,
          endpointData.method,
          endpointData.path_template,
          endpointData.query_template,
          endpointData.headers_json,
          endpointData.body_template,
          endpointData.parameters,
          endpointData.response_template
        );
      }
      
      showEndpointEditor = false;
      editingEndpoint = null;
      await loadAgent();  // Recarrega para atualizar lista
    } catch (err) {
      throw err;  // Propaga para o EndpointEditor mostrar
    }
  }
  
  async function handleEndpointDelete(endpoint) {
    if (!confirm(`Excluir endpoint "${endpoint.name}"?`)) {
      return;
    }
    
    try {
      await DeleteHTTPEndpoint(endpoint.id);
      await loadAgent();
    } catch (err) {
      error = 'Erro ao excluir endpoint: ' + (err.message || err);
    }
  }
  
  function openTestModal(endpoint) {
    testEndpoint = endpoint;
    testParams = '{}';
    testResult = '';
    testError = '';
    showTestModal = true;
  }
  
  async function runTest() {
    testing = true;
    testResult = '';
    testError = '';
    
    try {
      const result = await TestHTTPEndpoint(httpAgentId, testEndpoint.name, testParams);
      testResult = result;
    } catch (err) {
      testError = err.message || err;
    } finally {
      testing = false;
    }
  }
  
  function getMethodColor(method) {
    switch (method) {
      case 'GET': return '#61affe';
      case 'POST': return '#49cc90';
      case 'PUT': return '#fca130';
      case 'PATCH': return '#50e3c2';
      case 'DELETE': return '#f93e3e';
      default: return '#999';
    }
  }
</script>

<div class="http-agent-editor">
  {#if loading}
    <div class="loading">Carregando...</div>
  {:else}
    <div class="editor-header">
      <h2>{agentConfigId ? 'Editar HTTP Agent' : 'Novo HTTP Agent'}</h2>
      {#if agentConfigId}
        <button class="btn-delete" on:click={handleDelete}>
          🗑️ Excluir
        </button>
      {/if}
    </div>
    
    {#if error}
      <div class="error-message" role="alert">{error}</div>
    {/if}
    
    <div class="editor-content">
      <!-- Informações Básicas -->
      <section class="form-section">
        <h3>Informações Básicas</h3>
        
        <div class="form-row">
          <div class="form-group flex-1">
            <label for="agent-name">Nome (ID)</label>
            <input 
              type="text"
              id="agent-name"
              bind:value={name}
              placeholder="meu_api"
              disabled={!!agentConfigId}
              class="input-mono"
            />
          </div>
          <div class="form-group flex-1">
            <label for="agent-display-name">Nome de Exibição</label>
            <input 
              type="text"
              id="agent-display-name"
              bind:value={displayName}
              placeholder="Minha API"
            />
          </div>
        </div>
        
        <div class="form-group">
          <label for="agent-description">Descrição</label>
          <textarea 
            id="agent-description"
            bind:value={description}
            rows="2"
            placeholder="Descreva o que este agente faz..."
          ></textarea>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <label for="agent-model">Modelo LLM</label>
            <select id="agent-model" bind:value={model}>
              {#each availableModels as m}
                <option value={m}>{m}</option>
              {/each}
            </select>
          </div>
          <div class="form-group checkbox-group">
            <label>
              <input type="checkbox" bind:checked={enabled} />
              Habilitado
            </label>
          </div>
        </div>
      </section>
      
      <!-- Conexão -->
      <section class="form-section">
        <h3>Conexão</h3>
        
        <div class="form-group">
          <label for="base-url">URL Base</label>
          <input 
            type="text"
            id="base-url"
            bind:value={baseURL}
            placeholder="https://api.example.com/v1"
            class="input-mono"
          />
        </div>
        
        <div class="form-row">
          <div class="form-group flex-1">
            <label for="auth-type">Autenticação</label>
            <select id="auth-type" bind:value={authType}>
              {#each authTypes as at}
                <option value={at.value}>{at.label}</option>
              {/each}
            </select>
          </div>
          
          {#if authType === 'api_key'}
            <div class="form-group flex-1">
              <label for="auth-header">Nome do Header/Param</label>
              <input 
                type="text"
                id="auth-header"
                bind:value={authConfig.header_name}
                placeholder="X-API-Key"
              />
            </div>
            <div class="form-group flex-1">
              <label for="auth-value-env">Variável de Ambiente</label>
              <input 
                type="text"
                id="auth-value-env"
                bind:value={authConfig.value_env}
                placeholder="MY_API_KEY"
              />
            </div>
          {:else if authType === 'bearer'}
            <div class="form-group flex-1">
              <label for="token-env">Variável de Ambiente do Token</label>
              <input 
                type="text"
                id="token-env"
                bind:value={authConfig.token_env}
                placeholder="API_TOKEN"
              />
            </div>
          {:else if authType === 'basic'}
            <div class="form-group flex-1">
              <label for="username-env">Var. Ambiente Usuário</label>
              <input 
                type="text"
                id="username-env"
                bind:value={authConfig.username_env}
                placeholder="API_USER"
              />
            </div>
            <div class="form-group flex-1">
              <label for="password-env">Var. Ambiente Senha</label>
              <input 
                type="text"
                id="password-env"
                bind:value={authConfig.password_env}
                placeholder="API_PASS"
              />
            </div>
          {:else if authType === 'oauth2'}
            <div class="form-group flex-1">
              <label for="oauth-grant-type">Tipo de Grant</label>
              <select id="oauth-grant-type" bind:value={authConfig.grant_type}>
                {#each oauth2GrantTypes as gt}
                  <option value={gt.value}>{gt.label}</option>
                {/each}
              </select>
            </div>
          {/if}
        </div>
        
        {#if authType === 'oauth2'}
          <div class="oauth2-config">
            <div class="form-row">
              <div class="form-group flex-1">
                <label for="oauth-token-url">Token URL</label>
                <input 
                  type="text"
                  id="oauth-token-url"
                  bind:value={authConfig.token_url}
                  placeholder="https://oauth.example.com/token"
                  class="input-mono"
                />
              </div>
            </div>
            
            {#if authConfig.grant_type === 'authorization_code'}
              <div class="form-row">
                <div class="form-group flex-1">
                  <label for="oauth-authorize-url">Authorize URL</label>
                  <input 
                    type="text"
                    id="oauth-authorize-url"
                    bind:value={authConfig.authorize_url}
                    placeholder="https://oauth.example.com/authorize"
                    class="input-mono"
                  />
                </div>
              </div>
            {/if}
            
            <div class="form-row">
              <div class="form-group flex-1">
                <label for="oauth-client-id-env">Var. Ambiente Client ID</label>
                <input 
                  type="text"
                  id="oauth-client-id-env"
                  bind:value={authConfig.client_id_env}
                  placeholder="OAUTH_CLIENT_ID"
                />
              </div>
              <div class="form-group flex-1">
                <label for="oauth-client-secret-env">Var. Ambiente Client Secret</label>
                <input 
                  type="text"
                  id="oauth-client-secret-env"
                  bind:value={authConfig.client_secret_env}
                  placeholder="OAUTH_CLIENT_SECRET"
                />
              </div>
            </div>
            
            <div class="form-row">
              <div class="form-group flex-1">
                <label for="oauth-scopes">Scopes (separados por espaço)</label>
                <input 
                  type="text"
                  id="oauth-scopes"
                  bind:value={authConfig.scopes}
                  placeholder="read write admin"
                />
              </div>
              <div class="form-group flex-1">
                <label for="oauth-audience">Audience (opcional)</label>
                <input 
                  type="text"
                  id="oauth-audience"
                  bind:value={authConfig.audience}
                  placeholder="https://api.example.com"
                />
              </div>
            </div>
            
            <div class="form-group checkbox-inline">
              <label>
                <input 
                  type="checkbox" 
                  bind:checked={authConfig.send_credentials_in_body}
                />
                Enviar credenciais no body (em vez de Basic Auth header)
              </label>
            </div>
          </div>
        {/if}
        
        <div class="form-row">
          <div class="form-group">
            <label for="timeout">Timeout (segundos)</label>
            <input 
              type="number"
              id="timeout"
              bind:value={timeoutSeconds}
              min="1"
              max="300"
            />
          </div>
          <div class="form-group">
            <label for="retry">Tentativas</label>
            <input 
              type="number"
              id="retry"
              bind:value={retryCount}
              min="0"
              max="10"
            />
          </div>
        </div>
      </section>
      
      <!-- Headers Padrão -->
      <section class="form-section">
        <h3>
          Headers Padrão
          <button class="btn-add-small" on:click={addHeader} type="button">+ Adicionar</button>
        </h3>
        
        {#if defaultHeaders.length === 0}
          <p class="empty-hint">Nenhum header padrão. Headers são enviados em todas as requisições.</p>
        {:else}
          <div class="headers-list">
            {#each defaultHeaders as header, index}
              <div class="header-row">
                <input 
                  type="text"
                  bind:value={header.key}
                  placeholder="Content-Type"
                />
                <input 
                  type="text"
                  bind:value={header.value}
                  placeholder="application/json"
                />
                <button class="btn-remove" on:click={() => removeHeader(index)} type="button">✕</button>
              </div>
            {/each}
          </div>
        {/if}
      </section>
      
      <!-- Endpoints -->
      <section class="form-section">
        <h3>
          Endpoints (Funções)
          {#if httpAgentId}
            <button class="btn-add-small" on:click={() => openEndpointEditor(null)} type="button">+ Novo Endpoint</button>
          {/if}
        </h3>
        
        {#if !httpAgentId}
          <p class="empty-hint">Salve o agente primeiro para adicionar endpoints.</p>
        {:else if endpoints.length === 0}
          <p class="empty-hint">Nenhum endpoint configurado. Adicione endpoints para que o LLM possa chamar a API.</p>
        {:else}
          <div class="endpoints-list">
            {#each endpoints as endpoint}
              <div class="endpoint-card">
                <div class="endpoint-header">
                  <span class="method-badge" style="background: {getMethodColor(endpoint.method)}">
                    {endpoint.method}
                  </span>
                  <span class="endpoint-name">{endpoint.name}</span>
                </div>
                <div class="endpoint-path">{endpoint.path_template}</div>
                <div class="endpoint-description">{endpoint.description || 'Sem descrição'}</div>
                <div class="endpoint-actions">
                  <button class="btn-small" on:click={() => openTestModal(endpoint)}>🧪 Testar</button>
                  <button class="btn-small" on:click={() => openEndpointEditor(endpoint)}>✏️ Editar</button>
                  <button class="btn-small btn-danger" on:click={() => handleEndpointDelete(endpoint)}>🗑️</button>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </section>
    </div>
    
    <div class="editor-footer">
      <button class="btn-secondary" on:click={onClose} disabled={saving}>
        Cancelar
      </button>
      <button class="btn-primary" on:click={handleSave} disabled={saving}>
        {saving ? 'Salvando...' : 'Salvar Agente'}
      </button>
    </div>
  {/if}
</div>

<!-- Modal do EndpointEditor -->
<Modal 
  title={editingEndpoint ? 'Editar Endpoint' : 'Novo Endpoint'} 
  open={showEndpointEditor} 
  on:close={() => { showEndpointEditor = false; editingEndpoint = null; }}
>
  <EndpointEditor 
    endpoint={editingEndpoint}
    onSave={handleEndpointSave}
    onCancel={() => { showEndpointEditor = false; editingEndpoint = null; }}
    onTest={(ep) => { showEndpointEditor = false; openTestModal(ep); }}
  />
</Modal>

<!-- Modal de Teste -->
<Modal 
  title="🧪 Testar Endpoint: {testEndpoint?.name}" 
  open={showTestModal} 
  on:close={() => showTestModal = false}
>
  <div class="test-modal">
    <div class="form-group">
      <label>Parâmetros (JSON)</label>
      <textarea 
        bind:value={testParams}
        rows="4"
        placeholder={'{\n  "param1": "valor1"\n}'}
        class="input-mono"
      ></textarea>
    </div>
    
    <button class="btn-primary btn-full" on:click={runTest} disabled={testing}>
      {testing ? 'Executando...' : '▶️ Executar'}
    </button>
    
    {#if testError}
      <div class="test-error">
        <strong>Erro:</strong> {testError}
      </div>
    {/if}
    
    {#if testResult}
      <div class="test-result">
        <strong>Resultado:</strong>
        <pre>{testResult}</pre>
      </div>
    {/if}
  </div>
</Modal>

<style>
  .http-agent-editor {
    display: flex;
    flex-direction: column;
    height: 100%;
    max-height: 80vh;
  }
  
  .loading {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--spacing-xl);
    color: var(--color-text-muted);
  }
  
  .editor-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-bottom: var(--spacing-md);
    border-bottom: 1px solid var(--color-border);
  }
  
  .editor-header h2 {
    margin: 0;
    font-size: var(--font-size-xl);
  }
  
  .btn-delete {
    background: none;
    border: 1px solid var(--color-error);
    color: var(--color-error);
    padding: var(--spacing-xs) var(--spacing-sm);
    border-radius: var(--border-radius);
    cursor: pointer;
  }
  
  .error-message {
    margin: var(--spacing-md) 0;
    padding: var(--spacing-sm);
    background: rgba(248, 81, 73, 0.1);
    border: 1px solid var(--color-error);
    border-radius: var(--border-radius);
    color: var(--color-error);
  }
  
  .editor-content {
    flex: 1;
    overflow-y: auto;
    padding: var(--spacing-md) 0;
  }
  
  .form-section {
    border: 1px solid var(--color-border);
    border-radius: var(--border-radius);
    padding: var(--spacing-md);
    margin-bottom: var(--spacing-md);
  }
  
  .form-section h3 {
    margin: 0 0 var(--spacing-md);
    font-size: var(--font-size-md);
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
  }
  
  .btn-add-small {
    font-size: var(--font-size-xs);
    padding: 2px 8px;
    background: var(--color-accent);
    color: white;
    border: none;
    border-radius: var(--border-radius);
    cursor: pointer;
  }
  
  .form-row {
    display: flex;
    gap: var(--spacing-md);
    flex-wrap: wrap;
  }
  
  .flex-1 {
    flex: 1;
    min-width: 150px;
  }
  
  .form-group {
    margin-bottom: var(--spacing-md);
  }
  
  .form-group label {
    display: block;
    margin-bottom: var(--spacing-xs);
    font-weight: 500;
  }
  
  .form-group input,
  .form-group select,
  .form-group textarea {
    width: 100%;
    padding: var(--spacing-sm);
    border: 1px solid var(--color-border);
    border-radius: var(--border-radius);
    background: var(--color-bg-input);
    color: var(--color-text-primary);
  }
  
  .input-mono {
    font-family: 'Fira Code', monospace;
  }
  
  .checkbox-group label {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    cursor: pointer;
  }
  
  .checkbox-group input {
    width: auto;
  }
  
  .checkbox-inline {
    margin-top: var(--spacing-sm);
  }
  
  .checkbox-inline label {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    cursor: pointer;
    font-size: var(--font-size-sm);
  }
  
  .checkbox-inline input {
    width: auto;
  }
  
  .oauth2-config {
    margin-top: var(--spacing-md);
    padding: var(--spacing-md);
    background: var(--color-bg-tertiary);
    border-radius: var(--border-radius);
  }
  
  .empty-hint {
    color: var(--color-text-muted);
    font-size: var(--font-size-sm);
    margin: 0;
  }
  
  .headers-list {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-sm);
  }
  
  .header-row {
    display: flex;
    gap: var(--spacing-sm);
  }
  
  .header-row input {
    flex: 1;
    padding: var(--spacing-xs) var(--spacing-sm);
  }
  
  .btn-remove {
    background: none;
    border: none;
    color: var(--color-text-muted);
    cursor: pointer;
    padding: var(--spacing-xs);
  }
  
  .btn-remove:hover {
    color: var(--color-error);
  }
  
  .endpoints-list {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-sm);
  }
  
  .endpoint-card {
    border: 1px solid var(--color-border);
    border-radius: var(--border-radius);
    padding: var(--spacing-sm);
    background: var(--color-bg-tertiary);
  }
  
  .endpoint-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    margin-bottom: var(--spacing-xs);
  }
  
  .method-badge {
    padding: 2px 6px;
    border-radius: 3px;
    font-size: var(--font-size-xs);
    font-weight: 600;
    color: white;
  }
  
  .endpoint-name {
    font-weight: 600;
    font-family: 'Fira Code', monospace;
  }
  
  .endpoint-path {
    font-size: var(--font-size-sm);
    color: var(--color-text-muted);
    font-family: 'Fira Code', monospace;
  }
  
  .endpoint-description {
    font-size: var(--font-size-sm);
    color: var(--color-text-secondary);
    margin: var(--spacing-xs) 0;
  }
  
  .endpoint-actions {
    display: flex;
    gap: var(--spacing-xs);
    margin-top: var(--spacing-sm);
  }
  
  .btn-small {
    padding: 2px 8px;
    font-size: var(--font-size-xs);
    background: var(--color-bg-secondary);
    border: 1px solid var(--color-border);
    border-radius: var(--border-radius);
    cursor: pointer;
    color: var(--color-text-primary);
  }
  
  .btn-small.btn-danger {
    color: var(--color-error);
    border-color: var(--color-error);
  }
  
  .editor-footer {
    display: flex;
    justify-content: flex-end;
    gap: var(--spacing-sm);
    padding-top: var(--spacing-md);
    border-top: 1px solid var(--color-border);
  }
  
  .btn-primary, .btn-secondary {
    padding: var(--spacing-sm) var(--spacing-lg);
    border-radius: var(--border-radius);
    cursor: pointer;
    font-weight: 500;
  }
  
  .btn-primary {
    background: var(--color-accent);
    color: white;
    border: none;
  }
  
  .btn-secondary {
    background: var(--color-bg-tertiary);
    color: var(--color-text-primary);
    border: 1px solid var(--color-border);
  }
  
  /* Test Modal */
  .test-modal {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-md);
  }
  
  .btn-full {
    width: 100%;
  }
  
  .test-error {
    padding: var(--spacing-sm);
    background: rgba(248, 81, 73, 0.1);
    border-radius: var(--border-radius);
    color: var(--color-error);
  }
  
  .test-result {
    padding: var(--spacing-sm);
    background: var(--color-bg-tertiary);
    border-radius: var(--border-radius);
  }
  
  .test-result pre {
    margin: var(--spacing-sm) 0 0;
    overflow-x: auto;
    font-size: var(--font-size-sm);
    max-height: 300px;
    overflow-y: auto;
  }
</style>

// frontend/src/components/agents/HTTPAgentEditor.tsx
import { useState, useEffect } from 'react';
import {
  CreateHTTPAgentFull,
  GetHTTPAgentFull,
  UpdateHTTPAgentFull,
  DeleteHTTPAgentFull,
  GetHTTPEndpointsByAgentID,
  CreateHTTPEndpoint,
  UpdateHTTPEndpoint,
  DeleteHTTPEndpoint,
  TestHTTPEndpoint,
} from '../../../wailsjs/go/main/App';
import { Input } from '../ui/Input';
import { Textarea } from '../ui/Textarea';
import { Select } from '../ui/Select';
import { Checkbox } from '../ui/Checkbox';
import { Button } from '../ui/Button';
import { Modal } from '../ui/Modal';
import { EndpointEditor } from './EndpointEditor';
import './HTTPAgentEditor.css';

interface HTTPAgentEditorProps {
  agentConfigId?: number | null;
  onClose?: () => void;
  onSaved?: () => void;
  onDeleted?: () => void;
}

interface Header {
  key: string;
  value: string;
}

interface AuthConfig {
  [key: string]: any;
}

interface Endpoint {
  id: number;
  http_agent_id: number;
  name: string;
  description: string;
  method: string;
  path_template: string;
  query_template: string;
  headers_json: string;
  body_template: string;
  parameters: string;
  response_template: string;
}

const AUTH_TYPES = [
  { value: 'none', label: 'Sem autenticação' },
  { value: 'api_key', label: 'API Key' },
  { value: 'bearer', label: 'Bearer Token' },
  { value: 'basic', label: 'HTTP Basic' },
  { value: 'oauth2', label: 'OAuth 2.0' },
];

const OAUTH2_GRANT_TYPES = [
  { value: 'client_credentials', label: 'Client Credentials' },
  { value: 'authorization_code', label: 'Authorization Code (requer interação)' },
];

const AVAILABLE_MODELS = [
  'gpt-4o-mini',
  'gpt-4o',
  'gpt-4-turbo',
  'gpt-3.5-turbo',
];

export function HTTPAgentEditor({ agentConfigId, onClose, onSaved, onDeleted }: HTTPAgentEditorProps) {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  // AgentConfig fields
  const [name, setName] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [description, setDescription] = useState('');
  const [model, setModel] = useState('gpt-4o-mini');
  const [systemPrompt, setSystemPrompt] = useState('');
  const [enabled, setEnabled] = useState(true);

  // HTTPAgent fields
  const [baseURL, setBaseURL] = useState('');
  const [authType, setAuthType] = useState('none');
  const [authConfig, setAuthConfig] = useState<AuthConfig>({});
  const [defaultHeaders, setDefaultHeaders] = useState<Header[]>([]);
  const [timeoutSeconds, setTimeoutSeconds] = useState(30);
  const [retryCount, setRetryCount] = useState(3);

  // Endpoints
  const [endpoints, setEndpoints] = useState<Endpoint[]>([]);
  const [showEndpointEditor, setShowEndpointEditor] = useState(false);
  const [editingEndpoint, setEditingEndpoint] = useState<Endpoint | null>(null);

  useEffect(() => {
    console.log('HTTPAgentEditor - agentConfigId:', agentConfigId);
    if (agentConfigId) {
      loadAgent();
    } else {
      setLoading(false);
    }
  }, [agentConfigId]);

  const loadAgent = async () => {
    console.log('HTTPAgentEditor - loadAgent chamado com ID:', agentConfigId);
    setLoading(true);
    setError('');

    try {
      const agent = await GetHTTPAgentFull(agentConfigId!);
      console.log('HTTPAgentEditor - Agente carregado:', agent);

      setName(agent.name);
      setDisplayName(agent.display_name);
      setDescription(agent.description);
      setModel(agent.model || 'gpt-4o-mini');
      setSystemPrompt(agent.system_prompt || '');
      setEnabled(agent.enabled);

      setBaseURL(agent.base_url);
      setAuthType(agent.auth_type || 'none');
      setTimeoutSeconds(agent.timeout_seconds || 30);
      setRetryCount(agent.retry_count || 3);

      try {
        const parsedAuthConfig = agent.auth_config ? JSON.parse(agent.auth_config) : {};
        setAuthConfig(parsedAuthConfig);
      } catch {
        setAuthConfig({});
      }

      try {
        const headers = agent.default_headers ? JSON.parse(agent.default_headers) : {};
        const headersList = Object.entries(headers).map(([key, value]) => ({ key, value: value as string }));
        setDefaultHeaders(headersList);
      } catch {
        setDefaultHeaders([]);
      }

      // Carregar endpoints
      await loadEndpoints();
    } catch (err: any) {
      setError('Erro ao carregar agente: ' + (err.message || err));
    } finally {
      setLoading(false);
    }
  };

  const loadEndpoints = async () => {
    if (!agentConfigId) return;
    try {
      const endpointsList = await GetHTTPEndpointsByAgentID(agentConfigId);
      setEndpoints(endpointsList || []);
    } catch (err: any) {
      console.error('Erro ao carregar endpoints:', err);
    }
  };

  const handleSave = async () => {
    if (!name.trim()) {
      setError('Nome é obrigatório');
      return;
    }
    if (!displayName.trim()) {
      setError('Nome de exibição é obrigatório');
      return;
    }
    if (!baseURL.trim()) {
      setError('URL base é obrigatória');
      return;
    }

    setSaving(true);
    setError('');

    try {
      // Converte headers para JSON
      const headersObj: Record<string, string> = {};
      for (const h of defaultHeaders) {
        if (h.key.trim()) {
          headersObj[h.key.trim()] = h.value;
        }
      }
      const headersJSON = JSON.stringify(headersObj);
      const authConfigJSON = JSON.stringify(authConfig);

      if (agentConfigId) {
        // Atualiza existente
        await UpdateHTTPAgentFull(
          agentConfigId,
          displayName,
          description,
          model,
          systemPrompt,
          enabled,
          baseURL,
          authType,
          authConfigJSON,
          headersJSON,
          timeoutSeconds,
          retryCount
        );
      } else {
        // Cria novo
        await CreateHTTPAgentFull(
          name,
          displayName,
          description,
          model,
          systemPrompt,
          enabled,
          baseURL,
          authType,
          authConfigJSON,
          headersJSON,
          timeoutSeconds,
          retryCount
        );
      }

      onSaved?.();
      onClose?.();
    } catch (err: any) {
      setError('Erro ao salvar: ' + (err.message || err));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!window.confirm('Tem certeza que deseja excluir este agente HTTP e todos os seus endpoints?')) {
      return;
    }

    try {
      await DeleteHTTPAgentFull(agentConfigId!);
      onDeleted?.();
      onClose?.();
    } catch (err: any) {
      setError('Erro ao excluir: ' + (err.message || err));
    }
  };

  const addHeader = () => {
    setDefaultHeaders([...defaultHeaders, { key: '', value: '' }]);
  };

  const removeHeader = (index: number) => {
    setDefaultHeaders(defaultHeaders.filter((_, i) => i !== index));
  };

  const updateHeader = (index: number, field: 'key' | 'value', value: string) => {
    const updated = [...defaultHeaders];
    updated[index][field] = value;
    setDefaultHeaders(updated);
  };

  // Funções de gerenciamento de endpoints
  const handleNewEndpoint = () => {
    if (!agentConfigId) {
      alert('Salve o agente HTTP primeiro antes de adicionar endpoints.');
      return;
    }
    setEditingEndpoint(null);
    setShowEndpointEditor(true);
  };

  const handleEditEndpoint = (endpoint: Endpoint) => {
    setEditingEndpoint(endpoint);
    setShowEndpointEditor(true);
  };

  const handleDeleteEndpoint = async (endpointId: number) => {
    if (!window.confirm('Tem certeza que deseja excluir este endpoint?')) {
      return;
    }

    try {
      await DeleteHTTPEndpoint(endpointId);
      await loadEndpoints();
    } catch (err: any) {
      setError('Erro ao excluir endpoint: ' + (err.message || err));
    }
  };

  const handleSaveEndpoint = async (endpointData: any) => {
    try {
      if (endpointData.id) {
        // Atualizar
        await UpdateHTTPEndpoint(
          endpointData.id,
          endpointData.name,
          endpointData.description,
          endpointData.method,
          endpointData.pathTemplate,
          endpointData.queryTemplate,
          endpointData.headersJSON,
          endpointData.bodyTemplate,
          endpointData.parametersJSON,
          endpointData.responseTemplate
        );
      } else {
        // Criar novo
        await CreateHTTPEndpoint(
          agentConfigId!,
          endpointData.name,
          endpointData.description,
          endpointData.method,
          endpointData.pathTemplate,
          endpointData.queryTemplate,
          endpointData.headersJSON,
          endpointData.bodyTemplate,
          endpointData.parametersJSON,
          endpointData.responseTemplate
        );
      }
      
      setShowEndpointEditor(false);
      setEditingEndpoint(null);
      await loadEndpoints();
    } catch (err: any) {
      throw new Error('Erro ao salvar endpoint: ' + (err.message || err));
    }
  };

  const handleTestEndpoint = async (endpointData: any) => {
    try {
      // TestHTTPEndpoint precisa de 3 argumentos: id (number), params (string JSON), httpAgentId (string)
      const result = await TestHTTPEndpoint(endpointData.id, '{}', String(agentConfigId!));
      alert('Teste executado com sucesso!\n\n' + result);
    } catch (err: any) {
      alert('Erro ao testar endpoint:\n\n' + (err.message || err));
    }
  };

  const getMethodColor = (method: string) => {
    const colors: Record<string, string> = {
      GET: '#61affe',
      POST: '#49cc90',
      PUT: '#fca130',
      PATCH: '#50e3c2',
      DELETE: '#f93e3e',
    };
    return colors[method] || '#999';
  };

  if (loading) {
    return (
      <div className="http-agent-editor">
        <div className="loading-message">Carregando agente HTTP...</div>
      </div>
    );
  }

  return (
    <div className="http-agent-editor">
      <div className="editor-header">
        <h2>{agentConfigId ? 'Editar Agente HTTP' : 'Novo Agente HTTP'}</h2>
        <button className="close-button" onClick={onClose} aria-label="Fechar">×</button>
      </div>

      {error && <div className="error-message">{error}</div>}

      <div className="editor-content">
        {/* Informações Básicas */}
        <section className="editor-section">
          <h3>Informações Básicas</h3>
          
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="agent-name">Nome interno *</label>
              <Input
                id="agent-name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="http_agent_exemplo"
                disabled={!!agentConfigId}
              />
            </div>

            <div className="form-group">
              <label htmlFor="agent-display-name">Nome de exibição *</label>
              <Input
                id="agent-display-name"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                placeholder="Meu Agente HTTP"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="agent-description">Descrição</label>
            <Textarea
              id="agent-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Descrição do agente"
              rows={2}
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="agent-model">Modelo</label>
              <Select
                id="agent-model"
                value={model}
                onChange={(e) => setModel(e.target.value)}
                options={AVAILABLE_MODELS.map(m => ({ value: m, label: m }))}
              />
            </div>

            <div className="form-group checkbox-group">
              <Checkbox
                id="agent-enabled"
                checked={enabled}
                onChange={(e) => setEnabled(e.target.checked)}
                label="Agente ativo"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="agent-system-prompt">Prompt do sistema</label>
            <Textarea
              id="agent-system-prompt"
              value={systemPrompt}
              onChange={(e) => setSystemPrompt(e.target.value)}
              placeholder="Instruções para o agente..."
              rows={4}
            />
          </div>
        </section>

        {/* Configuração HTTP */}
        <section className="editor-section">
          <h3>Configuração HTTP</h3>

          <div className="form-group">
            <label htmlFor="base-url">URL Base *</label>
            <Input
              id="base-url"
              value={baseURL}
              onChange={(e) => setBaseURL(e.target.value)}
              placeholder="https://api.exemplo.com"
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="timeout">Timeout (segundos)</label>
              <Input
                id="timeout"
                type="number"
                value={timeoutSeconds.toString()}
                onChange={(e) => setTimeoutSeconds(parseInt(e.target.value) || 30)}
                min="1"
                max="300"
              />
            </div>

            <div className="form-group">
              <label htmlFor="retry-count">Tentativas de retry</label>
              <Input
                id="retry-count"
                type="number"
                value={retryCount.toString()}
                onChange={(e) => setRetryCount(parseInt(e.target.value) || 3)}
                min="0"
                max="10"
              />
            </div>
          </div>
        </section>

        {/* Autenticação */}
        <section className="editor-section">
          <h3>Autenticação</h3>

          <div className="form-group">
            <label htmlFor="auth-type">Tipo de autenticação</label>
            <Select
              id="auth-type"
              value={authType}
              onChange={(e) => setAuthType(e.target.value)}
              options={AUTH_TYPES}
            />
          </div>

          {authType === 'api_key' && (
            <>
              <div className="form-group">
                <label htmlFor="api-key-header">Nome do header</label>
                <Input
                  id="api-key-header"
                  value={authConfig.header_name || 'X-API-Key'}
                  onChange={(e) => setAuthConfig({ ...authConfig, header_name: e.target.value })}
                  placeholder="X-API-Key"
                />
              </div>
              <div className="form-group">
                <label htmlFor="api-key-value">Valor da chave</label>
                <Input
                  id="api-key-value"
                  type="password"
                  value={authConfig.api_key || ''}
                  onChange={(e) => setAuthConfig({ ...authConfig, api_key: e.target.value })}
                  placeholder="sua-api-key"
                />
              </div>
            </>
          )}

          {authType === 'bearer' && (
            <div className="form-group">
              <label htmlFor="bearer-token">Token Bearer</label>
              <Input
                id="bearer-token"
                type="password"
                value={authConfig.token || ''}
                onChange={(e) => setAuthConfig({ ...authConfig, token: e.target.value })}
                placeholder="seu-token"
              />
            </div>
          )}

          {authType === 'basic' && (
            <>
              <div className="form-group">
                <label htmlFor="basic-username">Usuário</label>
                <Input
                  id="basic-username"
                  value={authConfig.username || ''}
                  onChange={(e) => setAuthConfig({ ...authConfig, username: e.target.value })}
                  placeholder="usuário"
                />
              </div>
              <div className="form-group">
                <label htmlFor="basic-password">Senha</label>
                <Input
                  id="basic-password"
                  type="password"
                  value={authConfig.password || ''}
                  onChange={(e) => setAuthConfig({ ...authConfig, password: e.target.value })}
                  placeholder="senha"
                />
              </div>
            </>
          )}

          {authType === 'oauth2' && (
            <>
              <div className="form-group">
                <label htmlFor="oauth-grant-type">Grant Type</label>
                <Select
                  id="oauth-grant-type"
                  value={authConfig.grant_type || 'client_credentials'}
                  onChange={(e) => setAuthConfig({ ...authConfig, grant_type: e.target.value })}
                  options={OAUTH2_GRANT_TYPES}
                />
              </div>
              <div className="form-group">
                <label htmlFor="oauth-token-url">Token URL</label>
                <Input
                  id="oauth-token-url"
                  value={authConfig.token_url || ''}
                  onChange={(e) => setAuthConfig({ ...authConfig, token_url: e.target.value })}
                  placeholder="https://oauth.exemplo.com/token"
                />
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="oauth-client-id">Client ID</label>
                  <Input
                    id="oauth-client-id"
                    value={authConfig.client_id || ''}
                    onChange={(e) => setAuthConfig({ ...authConfig, client_id: e.target.value })}
                    placeholder="client-id"
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="oauth-client-secret">Client Secret</label>
                  <Input
                    id="oauth-client-secret"
                    type="password"
                    value={authConfig.client_secret || ''}
                    onChange={(e) => setAuthConfig({ ...authConfig, client_secret: e.target.value })}
                    placeholder="client-secret"
                  />
                </div>
              </div>
            </>
          )}
        </section>

        {/* Headers Padrão */}
        <section className="editor-section">
          <div className="section-header">
            <h3>Headers Padrão</h3>
            <Button onClick={addHeader} variant="secondary" size="sm">
              + Adicionar header
            </Button>
          </div>

          <div className="headers-list">
            {defaultHeaders.map((header, index) => (
              <div key={index} className="header-row">
                <Input
                  value={header.key}
                  onChange={(e) => updateHeader(index, 'key', e.target.value)}
                  placeholder="Nome do header"
                />
                <Input
                  value={header.value}
                  onChange={(e) => updateHeader(index, 'value', e.target.value)}
                  placeholder="Valor"
                />
                <button
                  type="button"
                  className="remove-button"
                  onClick={() => removeHeader(index)}
                  aria-label="Remover header"
                >
                  ×
                </button>
              </div>
            ))}
            {defaultHeaders.length === 0 && (
              <div className="empty-message">Nenhum header configurado</div>
            )}
          </div>
        </section>

        {/* Endpoints */}
        {agentConfigId && (
          <section className="editor-section">
            <div className="section-header">
              <h3>Endpoints</h3>
              <Button onClick={handleNewEndpoint} variant="secondary" size="sm">
                + Adicionar endpoint
              </Button>
            </div>

            <div className="endpoints-list">
              {endpoints.length === 0 ? (
                <div className="empty-message">
                  Nenhum endpoint configurado. Adicione o primeiro para que o agente possa fazer chamadas à API.
                </div>
              ) : (
                <div className="endpoints-table">
                  <div className="endpoints-table-header">
                    <div className="col-method">Método</div>
                    <div className="col-name">Nome</div>
                    <div className="col-path">Path</div>
                    <div className="col-actions">Ações</div>
                  </div>
                  {endpoints.map((endpoint) => (
                    <div key={endpoint.id} className="endpoints-table-row">
                      <div className="col-method">
                        <span 
                          className="method-badge" 
                          style={{ backgroundColor: getMethodColor(endpoint.method) }}
                        >
                          {endpoint.method}
                        </span>
                      </div>
                      <div className="col-name">{endpoint.name}</div>
                      <div className="col-path">{endpoint.path_template}</div>
                      <div className="col-actions">
                        <button
                          onClick={() => handleEditEndpoint(endpoint)}
                          className="action-button edit"
                          title="Editar"
                        >
                          ✏️
                        </button>
                        <button
                          onClick={() => handleDeleteEndpoint(endpoint.id)}
                          className="action-button delete"
                          title="Excluir"
                        >
                          🗑️
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </section>
        )}
      </div>

      {/* Ações */}
      <div className="editor-actions">
        <div className="actions-left">
          {agentConfigId && (
            <Button onClick={handleDelete} variant="danger">
              Excluir agente
            </Button>
          )}
        </div>
        <div className="actions-right">
          <Button onClick={onClose} variant="secondary">
            Cancelar
          </Button>
          <Button onClick={handleSave} disabled={saving}>
            {saving ? 'Salvando...' : agentConfigId ? 'Salvar' : 'Criar'}
          </Button>
        </div>
      </div>

      {/* Modal do EndpointEditor */}
      {showEndpointEditor && (
        <Modal
          id="endpoint-editor-modal"
          title={editingEndpoint ? 'Editar Endpoint' : 'Novo Endpoint'}
          onClose={() => {
            setShowEndpointEditor(false);
            setEditingEndpoint(null);
          }}
          size="xl"
        >
          <EndpointEditor
            endpoint={editingEndpoint}
            agentId={agentConfigId || undefined}
            onSave={handleSaveEndpoint}
            onCancel={() => {
              setShowEndpointEditor(false);
              setEditingEndpoint(null);
            }}
            onTest={editingEndpoint ? handleTestEndpoint : undefined}
          />
        </Modal>
      )}
    </div>
  );
}
