// frontend/src/components/pickers/ModelPicker.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import { GetModels } from '../../../wailsjs/go/main/App.js';
  import { Combobox as ComboboxPicker } from '../combobox';

  const dispatch = createEventDispatcher();

  // Props
  export let value = '';
  export let label = 'Modelo';
  export let icon = '🤖';
  export let placeholder = 'Filtrar modelos...';
  export let disabled = false;
  export let allowCustom = false;
  export let maxWidth = '180px';
  
  // Variante: 'toolbar' (compacto) ou 'form' (com label e help)
  export let variant = 'toolbar';
  export let helpText = '';

  // Estado
  let models = [];
  let loading = true;
  let error = '';
  let pickerComponent;

  // Items formatados para o ComboboxPicker
  $: items = models.map(m => ({ value: m, label: m }));

  onMount(async () => {
    await loadModels();
  });

  async function loadModels() {
    loading = true;
    error = '';
    try {
      models = await GetModels() || [];
    } catch (e) {
      error = 'Erro ao carregar modelos';
      console.error('ModelPicker: erro ao carregar modelos', e);
    } finally {
      loading = false;
    }
  }

  function handleSelect(event) {
    value = event.detail.value;
    dispatch('select', event.detail);
    dispatch('change', value);
  }

  function handleAnnounce(event) {
    dispatch('announce', event.detail);
  }

  // Expõe métodos do picker
  export function open() {
    pickerComponent?.open();
  }

  export function close() {
    pickerComponent?.close();
  }

  export function reload() {
    loadModels();
  }
</script>

{#if variant === 'form'}
  <div class="model-picker-form">
    <label for="model-picker-{label}">{label}</label>
    
    {#if loading}
      <div class="loading-state">
        <span class="loading-spinner"></span>
        Carregando modelos...
      </div>
    {:else if error}
      <div class="error-state">
        <span>{error}</span>
        <button type="button" class="retry-btn" on:click={loadModels}>
          🔄 Tentar novamente
        </button>
      </div>
    {:else}
      <ComboboxPicker
        bind:this={pickerComponent}
        {icon}
        label={value || 'Selecionar modelo'}
        {items}
        bind:selected={value}
        {placeholder}
        {disabled}
        maxWidth="100%"
        on:select={handleSelect}
        on:announce={handleAnnounce}
      />
    {/if}
    
    {#if helpText}
      <small class="help-text">{helpText}</small>
    {/if}
  </div>
{:else}
  <!-- Variante toolbar (compacta) -->
  {#if loading}
    <div class="loading-status">
      <span class="loading-spinner"></span>
      Carregando...
    </div>
  {:else if error}
    <button class="toolbar-btn error-btn" on:click={loadModels}>
      🔄 Recarregar
    </button>
  {:else}
    <ComboboxPicker
      bind:this={pickerComponent}
      {icon}
      {label}
      {items}
      bind:selected={value}
      {placeholder}
      {disabled}
      {maxWidth}
      on:select={handleSelect}
      on:announce={handleAnnounce}
    />
  {/if}
{/if}

<style>
  .model-picker-form {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .model-picker-form label {
    font-weight: 500;
    color: var(--color-text-primary, #e0e0e0);
  }

  .loading-state,
  .error-state {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    padding: var(--spacing-sm);
    color: var(--color-text-muted);
    font-size: var(--font-size-sm);
  }

  .error-state {
    color: var(--color-error, #f85149);
  }

  .retry-btn {
    padding: var(--spacing-xs) var(--spacing-sm);
    background: transparent;
    border: 1px solid currentColor;
    border-radius: var(--border-radius);
    color: inherit;
    cursor: pointer;
    font-size: var(--font-size-xs);
  }

  .retry-btn:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  .help-text {
    color: var(--color-text-muted, #888);
    font-size: 0.85rem;
  }

  .loading-status {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    padding: var(--spacing-sm);
    color: var(--color-text-muted);
    font-size: var(--font-size-sm);
  }

  .loading-spinner {
    display: inline-block;
    width: 14px;
    height: 14px;
    border: 2px solid var(--color-border, #444);
    border-top-color: var(--color-accent, #58a6ff);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .error-btn {
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    padding: var(--spacing-xs) var(--spacing-sm);
    background: var(--color-bg-secondary);
    border: 1px solid var(--color-error, #f85149);
    border-radius: var(--border-radius);
    color: var(--color-error, #f85149);
    font-size: var(--font-size-sm);
    cursor: pointer;
  }

  .error-btn:hover {
    background: rgba(248, 81, 73, 0.1);
  }

  /* Estilo para o ComboboxPicker quando em modo form */
  .model-picker-form :global(.combobox-picker) {
    width: 100%;
  }

  .model-picker-form :global(.picker-button) {
    width: 100%;
    max-width: none;
  }
</style>

// frontend/src/components/pickers/ModelPicker.tsx
import { useState, useEffect, useImperativeHandle, forwardRef } from 'react';
import { GetModels } from '@wailsjs/go/main/App';
import { Combobox, ComboboxItem } from './Combobox';
import './ModelPicker.css';

export interface ModelPickerProps {
    value: string;
    onChange: (value: string) => void;
    label?: string;
    icon?: string;
    placeholder?: string;
    disabled?: boolean;
    maxWidth?: string;
    variant?: 'toolbar' | 'form';
    helpText?: string;
    onAnnounce?: (message: string) => void;
}

export interface ModelPickerRef {
    reload: () => void;
}

export const ModelPicker = forwardRef<ModelPickerRef, ModelPickerProps>(({
    value,
    onChange,
    label = 'Modelo',
    icon = '🤖',
    placeholder = 'Filtrar modelos...',
    disabled = false,
    maxWidth = '180px',
    variant = 'toolbar',
    helpText = '',
    onAnnounce
}, ref) => {
    const [models, setModels] = useState<string[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    const loadModels = async () => {
        setLoading(true);
        setError('');
        try {
            const modelsList = await GetModels() || [];
            setModels(modelsList);
        } catch (e) {
            setError('Erro ao carregar modelos');
            console.error('ModelPicker: erro ao carregar modelos', e);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        loadModels();
    }, []);

    // Expõe método reload
    useImperativeHandle(ref, () => ({
        reload: loadModels
    }));

    // Items formatados para o Combobox
    const items: ComboboxItem[] = models.map(m => ({ value: m, label: m }));

    const handleSelect = (selectedValue: string) => {
        onChange(selectedValue);
    };

    if (variant === 'form') {
        return (
            <div className="model-picker-form">
                <label htmlFor={`model-picker-${label}`}>{label}</label>

                {loading ? (
                    <div className="loading-state" role="status" aria-live="polite">
                        <span className="loading-spinner" aria-hidden="true"></span>
                        Carregando modelos...
                    </div>
                ) : error ? (
                    <div className="error-state" role="alert">
                        <span>{error}</span>
                        <button type="button" className="retry-btn" onClick={loadModels}>
                            🔄 Tentar novamente
                        </button>
                    </div>
                ) : (
                    <Combobox
                        icon={icon}
                        label={label}
                        items={items}
                        selected={value}
                        onSelect={handleSelect}
                        placeholder={placeholder}
                        disabled={disabled}
                        maxWidth="100%"
                        onAnnounce={onAnnounce}
                    />
                )}

                {helpText && <p className="help-text">{helpText}</p>}
            </div>
        );
    }

    // Variant toolbar (compacto)
    if (loading) {
        return (
            <div className="model-picker-toolbar loading" role="status" aria-live="polite">
                <span className="loading-spinner" aria-hidden="true"></span>
                <span>Carregando...</span>
            </div>
        );
    }

    if (error) {
        return (
            <div className="model-picker-toolbar error" role="alert">
                <span>❌ Erro</span>
            </div>
        );
    }

    return (
        <Combobox
            icon={icon}
            label={label}
            items={items}
            selected={value}
            onSelect={handleSelect}
            placeholder={placeholder}
            disabled={disabled}
            maxWidth={maxWidth}
            onAnnounce={onAnnounce}
        />
    );
});

ModelPicker.displayName = 'ModelPicker';
